import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";
import vm from "node:vm";
import ts from "typescript";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");

function transpileModule(sourcePath, requires = {}) {
  const source = readFileSync(sourcePath, "utf8");
  const transpiled = ts.transpileModule(source, {
    compilerOptions: {
      module: ts.ModuleKind.CommonJS,
      target: ts.ScriptTarget.ES2022,
      esModuleInterop: true,
    },
    fileName: sourcePath,
  }).outputText;
  const cjsModule = { exports: {} };
  const sandbox = {
    module: cjsModule,
    exports: cjsModule.exports,
    require(specifier) {
      if (specifier in requires) return requires[specifier];
      throw new Error(`Unexpected require from ${sourcePath}: ${specifier}`);
    },
    Date,
    JSON,
    String,
    Object,
    Array,
    Set,
    RegExp,
    console,
  };
  vm.runInNewContext(transpiled, sandbox, { filename: sourcePath });
  return cjsModule.exports;
}

test("Loop execution and retry instructions preserve the exact original input and explicit restrictions", () => {
  const instructionModule = transpileModule(resolve(repoRoot, "src/lib/loops/execution-instruction.ts"));
  const originalInput = "  No modificar archivos ni servicios.\nRespetar este input exactamente.  ";
  const loop = {
    id: "loop-1",
    name: "Safe diagnosis",
    summary: "Summary generated by planning",
    description: "Description generated by planning",
    target_outcome: "Return a diagnosis",
    plan: [{ title: "Inspect only", status: "pending", notes: "No writes" }],
    metadata: { original_input: originalInput },
    approval_scope: {
      allowed_actions: ["read", "diagnose"],
      forbidden_actions: ["modify_files", "restart_services"],
      notes: "Read-only execution",
    },
  };

  const materialized = instructionModule.buildLoopExecutionInstruction(loop);
  const retry = instructionModule.buildLoopReworkInstruction(loop, "Clarify the diagnosis", "loop-1");
  const wake = instructionModule.buildLoopWakeContext(loop);

  for (const instruction of [materialized, retry, wake]) {
    assert.equal(instruction.includes(originalInput), true, "verbatim original input was lost");
    assert.match(instruction, /Forbidden actions:\n- modify_files\n- restart_services/);
    assert.match(instruction, /Allowed actions:\n- read\n- diagnose/);
    assert.match(instruction, /Read-only execution/);
  }
  assert.match(retry, /Clarify the diagnosis/);
});

test("Loop creation stores the request byte-for-byte instead of only normalized planning fields", async () => {
  let insertedLoopParams;
  let eventParams;
  const createRoute = transpileModule(resolve(repoRoot, "src/app/api/loops/create/route.ts"), {
    "next/server": { NextResponse: { json: (payload, init = {}) => ({ payload, status: init.status || 200 }) } },
    "@/lib/auth/local": {
      getLocalMissionControlUser: () => ({ email: "creator@example.test" }),
      isLocalAuthDisabled: () => true,
    },
    "@/lib/db/postgres": {
      withTransaction: async (run) => run({
        async query(sql, params = []) {
          const normalized = sql.replace(/\s+/g, " ").trim().toLowerCase();
          if (normalized.includes("pg_advisory_xact_lock")) return { rows: [] };
          if (normalized.startsWith("select id, key, status from loops")) return { rows: [] };
          if (normalized.startsWith("select key from loops")) return { rows: [] };
          if (normalized.startsWith("insert into loops")) {
            insertedLoopParams = params;
            return { rows: [{ id: "loop-1", key: "safe-loop", status: "planning" }] };
          }
          if (normalized.startsWith("insert into loop_events")) {
            eventParams = params;
            return { rows: [] };
          }
          throw new Error(`Unexpected create SQL: ${normalized}`);
        },
      }),
    },
    pg: {},
    "@/lib/supabase/server": { createClient: async () => { throw new Error("unexpected cloud auth"); } },
    "@/lib/supabase/admin": { createServiceClient: () => { throw new Error("unexpected cloud client"); } },
  });
  const originalInput = "  No modificar archivos ni servicios.\nMantener espacios finales.  ";

  const response = await createRoute.POST({ json: async () => ({ input: originalInput }) });

  assert.equal(response.status, 200);
  assert.equal(insertedLoopParams[1], originalInput);
  assert.equal(JSON.parse(insertedLoopParams[4]).original_input, originalInput);
  assert.equal(JSON.parse(eventParams[2]).input, originalInput);
});

test("Loop read model does not persist primary-execution lifecycle transitions", () => {
  const source = readFileSync(resolve(repoRoot, "src/lib/loops/read-model.ts"), "utf8");
  assert.doesNotMatch(source, /reconcileLoopStatusWithPrimaryExecution(?:Local)?/);
  assert.doesNotMatch(source, /system:read_model/);
});
